"""License / activation key model. Keys are generated by the vendor (super_admin),
emailed to the customer, and validated by the installer before setup runs."""
from datetime import date
from typing import Optional

from sqlalchemy import String, Boolean, Integer, Date, Text
from sqlalchemy.orm import Mapped, mapped_column

from core.database import Base
from .base import TimestampMixin


class LicenseKey(Base, TimestampMixin):
    __tablename__ = 'license_keys'

    id:                 Mapped[int]           = mapped_column(Integer, primary_key=True)
    key:                Mapped[str]           = mapped_column(String(40), unique=True, index=True)
    customer:           Mapped[str]           = mapped_column(String(200))
    email:              Mapped[Optional[str]] = mapped_column(String(254), nullable=True)
    edition:            Mapped[str]           = mapped_column(String(30), default='ALIS-X')
    expires_at:         Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    revoked:            Mapped[bool]          = mapped_column(Boolean, default=False)
    activated:          Mapped[bool]          = mapped_column(Boolean, default=False)
    activated_facility: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)
    issued_by_id:       Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    notes:              Mapped[Optional[str]] = mapped_column(Text, nullable=True)
